mysql:
    container_name: thulcandra-mysql
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "3306:3306"
    volumes:
        - "./mysql/scripts:/docker-entrypoint-initdb.d"
